import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";

const roboto = Roboto_Slab({
   weight: '200',
   subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={roboto.className}>
      {/* <body className={roboto.className}> */}
        {children}
        <Navbar />
      </body>
    </html>
  );
}
